/**
 * Phase 4 — automatic monthly roster generator.
 *
 * Given a fleet type and a pool of candidate pairings for one calendar
 * month (already generated by Phase 2's `generatePairings`, filtered to
 * that fleet), produces a full day-by-day FLIGHT/OFF assignment for the
 * whole month, provably GCAA-compliant *by construction* (every candidate
 * is screened against the real Phase 3 evaluator before being accepted),
 * plus an independent post-generation verification pass that re-runs
 * `evaluateDuty()` against the finished result.
 *
 * SCOPE (see docs/roster-gen-assumptions.md for the full list): this is a
 * personal-tool, single-month, greedy day-by-day generator — not a global
 * optimizer, and not a full CSP solver. It explicitly does NOT:
 *   - account for the 12-month rolling cumulative limits (900h/12mo block
 *     time) — this tool has no prior-month history to compute a real
 *     rolling 12-month figure from. `CumulativeTotals.blockMinutes12mo` is
 *     filled with this month's own running total as a documented stand-in
 *     (always far below the 900h ceiling for a single month, so this never
 *     produces a false RED — it just isn't a real cross-month check).
 *   - model any Emirates-specific FTL Variation / augmented-crew scheme
 *     (consistent with Phase 3's own `OPERATOR_SPECIFIC` marking in
 *     `src/ftl/rules/operatorSpecific.ts`).
 *   - try to be globally optimal (maximize pay, minimize fatigue beyond the
 *     hard legal floor, etc.) — it produces *a* compliant roster, not *the
 *     best* one.
 *   - track real acclimatisation history (`src/ftl/rules/acclimatisation.ts`
 *     needs consecutive-local-night history this generator doesn't keep);
 *     every duty is assumed `isAcclimatised: true` (Table A limits), a
 *     simplification applied identically during both construction-time
 *     screening and the final verification pass, so it cannot itself cause
 *     construction/verification disagreement.
 *   - **EXTENDED by item 24 — see the "CROSS-MONTH REST + CONSECUTIVE-
 *     DUTY-DAY CARRY-OVER" section below; the original text is preserved
 *     as what still applies whenever `priorMonthTailDays` is absent.**
 *     assume anything about the crew member's rest state before day 1 of
 *     the month (no prior-month history) — the very first duty of the
 *     month is never rest-checked against a "previous" duty.
 *
 * ALGORITHM: greedy day-by-day walk (see module functions below). At each
 * unoccupied day, candidate pairings starting that day are tried (in a
 * deterministically shuffled order, for route variety) and accepted the
 * moment one is found that (a) fits in the remaining days of the month,
 * (b) keeps `consecutiveDutyDays` at or below 7, and (c) produces zero RED
 * `RuleEvaluation`s when the *real* `evaluateDuty()` is run against every
 * day it would occupy (FDP-table, minimum rest, and the cumulative
 * block/duty-hour ceilings). If no candidate fits, the day is OFF.
 *
 * HARD BLOCK-HOURS TARGET RANGE + SELECTABLE STRATEGY: when
 * `input.targetBlockMinutesMax` is set, it is enforced as a HARD
 * eligibility filter (see `filterCandidatesWithinBudget`), applied BEFORE
 * any ordering: a candidate is only eligible for a day if
 * `runningBlockMinutesSoFar + candidateBlockMinutes <=
 * targetBlockMinutesMax`. If no candidate is eligible (illegal, doesn't
 * fit the remaining month, or doesn't fit the remaining budget), the day is
 * OFF — this can leave the month under `targetBlockMinutesMin` at month
 * end, which is an accepted outcome, never an error (per explicit user
 * priority: prefer an OFF day over exceeding the ceiling).
 * `targetBlockMinutesMin` itself is NOT enforced as a filter — it is
 * informational only.
 *
 * Among the day's already-budget-filtered eligible candidates,
 * `input.generationStrategy` (default `'MIX'`) picks which one is tried
 * first (see `orderCandidatesByStrategy` and `GenerationStrategy`'s doc
 * comment in types.ts): `MIX` prefers the haul type
 * (`haulType.ts#classifyHaulType`) least-represented among pairings
 * assigned so far this month; `MAX_FLYING` prefers the smaller block-time
 * candidate (more distinct flying days for the same budget); `MAX_DAYS_OFF`
 * prefers the bigger block-time candidate (fewer trips, more days off).
 * This never changes (a)/(b)/(c) above — the budget filter and strategy
 * ordering only narrow/reorder which already-legal candidate is tried
 * first among the day's eligible options. See
 * docs/roster-gen-assumptions.md item 20 (item 19, preserved for history,
 * describes the prior soft-bias design this replaces).
 * `consecutiveDutyDays >= 6` pre-emptively forces an OFF day (margin below
 * the legal 7-day ceiling), and from day 24 onward an OFF day is forced
 * whenever the days-off pace could not otherwise reach the
 * `TARGET_DAYS_OFF_PER_MONTH` target by month end (see
 * `evaluateRosterDays` for why the "days off in any N days" checks are
 * suppressed until a full N-day window of *this* roster has elapsed —
 * they are not well-defined against a partial window with no prior-month
 * history, and this generator does not fabricate one).
 *
 * WEEKLY-BLOCK PACING (docs/roster-gen-assumptions.md item 21, extending
 * items 3 and 20): the month-level checks above are necessary but not
 * sufficient — a purely day-by-day greedy walk can legally spend the ENTIRE
 * `targetBlockMinutesMax` budget in the first 2-3 weeks (nothing above stops
 * it), forcing every remaining day of the month OFF as one giant tail once
 * the budget runs out. This was diagnosed against the user's real live
 * October 2026 roster (10 consecutive OFF days at the end of the month) and
 * is fixed by two ADDITIONAL, narrower eligibility/pacing layers, both
 * scoped to simple sequential 7-day-from-day-1 "week slices" (NOT calendar
 * ISO weeks — see `numberOfWeekSlices`/`weekSliceBoundsForDay`):
 *
 *   1. When `targetBlockMinutesMax` is set, each week slice additionally
 *      gets its own soft block-minutes slice (`targetBlockMinutesMax /
 *      numberOfWeekSlices`, flat division) plus a 50% tolerance
 *      (`WEEKLY_BLOCK_TOLERANCE_FRACTION`) — see
 *      `filterCandidatesWithinWeeklyBudget`. This runs BESIDE (never
 *      instead of) the existing month-level `filterCandidatesWithinBudget`;
 *      a candidate must pass BOTH.
 *   2. Independent of `targetBlockMinutesMax`, each week slice also gets its
 *      own OFF-day target (`TARGET_DAYS_OFF_PER_MONTH` scaled to the
 *      slice's own length, so a short trailing remainder slice isn't held to
 *      a full week's target) — see `targetOffDaysForWeekSlice`. Exactly like
 *      the existing month-level `PACING_CHECK_FROM_DAY` check, this forces
 *      OFF as soon as it becomes mathematically necessary to still hit that
 *      slice's own target before the slice ends, not only on the slice's
 *      literal last day.
 *
 * Both layers only ever narrow eligibility or force OFF sooner — they never
 * turn an illegal candidate legal, and they stack with (never replace) every
 * check above: a day goes OFF if ANY forcing condition or empty-eligible-set
 * condition says so.
 *
 * NATURAL OFF-BLOCK VARIATION (docs/roster-gen-assumptions.md item 22,
 * extending item 21's layer 2 only): layer 2 above, as originally built, is
 * a purely deterministic "fire on exactly this day" trigger, which turned
 * out to produce mechanically-uniform OFF blocks — every block exactly
 * `weeklyTargetOffDays` long, every time (diagnosed against the user's real
 * live October 2026 roster: `FFFFFOOFFFFOOFFFFFOOFFFFFFOOFFO`, EVERY OFF
 * block exactly 2 days). Direct user feedback: 2-4 days off between flying
 * blocks is normal as an AVERAGE, not something to enforce as a rule — the
 * fix is to make the trigger itself vary, using the existing seeded
 * `mulberry32` PRNG mechanism (never `Math.random()`), never a hard
 * min/max block-length check. Two independent, additive knobs, both scoped
 * STRICTLY to layer 2's own trigger (`forcedOffByWeeklyPacing` below) —
 * neither ever touches layer 1 (`filterCandidatesWithinWeeklyBudget`,
 * unchanged), the month-level `PACING_CHECK_FROM_DAY` check,
 * `CONSECUTIVE_DUTY_DAYS_SOFT_CAP`, or any `evaluateDuty()` legality
 * screen — both only ever turn an already-OFF-eligible day OFF sooner, or
 * keep an already-started weekly-pacing OFF streak going one extra day,
 * never the reverse:
 *
 *   1. TRIGGER-WINDOW JITTER (`rollWeeklyPacingTriggerSlackDays`) — rolled
 *      ONCE per week slice, this lets the weekly pacing trigger fire up to
 *      `WEEKLY_PACING_TRIGGER_SLACK_MAX_DAYS` days earlier than the
 *      mathematically-latest-possible day within the slice, varying block
 *      POSITION. The `weeklyStillNeededOff > 0` guard is required: without
 *      it, near a slice's own last `slack` days the slacked comparison
 *      would fire even after the slice's target is already met, forcing
 *      unneeded extra OFF days — the guard makes slack only ever pull a
 *      genuinely still-needed trigger earlier, never invent a new one.
 *   2. STREAK-LENGTH EXTENSION (`rollOffStreakExtensionDays`) — rolled once
 *      whenever a fresh OFF streak actually STARTS because of the weekly
 *      pacing trigger specifically (never for a layer-1/legality/
 *      consecutive-cap-caused "no eligible candidate" OFF day, and never
 *      re-rolled while a streak is already running), this gives a
 *      probabilistic chance of continuing that streak
 *      `OFF_STREAK_EXTENSION_MAX_DAYS` extra days beyond the mechanical
 *      minimum the trigger alone would produce, varying block LENGTH
 *      (jitter alone only varies block position, not length — once the
 *      trigger fires, `weeklyStillNeededOff` and `remainingDaysInSlice`
 *      decrease in lockstep every forced day, so the streak's own length is
 *      fixed by how much was still needed at the moment it fired,
 *      independent of when that moment was). Combined with the ~2-day
 *      mechanical minimum this generator's own constants tend to produce,
 *      typical total block length lands in the 2-4 day range the user
 *      described as normal — without ever hard-rejecting a shorter or
 *      longer block if that is what the actual legal/budget situation
 *      produces; there is no `if (blockLength < 2 || blockLength > 4)
 *      reject` anywhere in this file, deliberately.
 *
 * Both draw from a SEPARATE seeded `mulberry32` stream
 * (`weeklyPacingVariationRng`, seeded from
 * `${fleetType}|${year}|${month}|weekly-pacing-variation`) rather than
 * reusing the candidate-shuffle `rng` above, so the two concerns stay
 * decoupled — adding/removing one never perturbs the other's draw
 * sequence — while both remain fully deterministic and reproducible for a
 * given fleet/year/month, per this generator's existing seeding discipline
 * (docs/roster-gen-assumptions.md item 7).
 *
 * ENFORCED MIN BLOCK-HOURS FLOOR (docs/roster-gen-assumptions.md item 23):
 * `targetBlockMinutesMin` used to be purely informational (see the "HARD
 * BLOCK-HOURS TARGET RANGE" section above) — a month could legitimately land
 * under it if the day-by-day walk simply never needed to fly enough. Direct
 * user feedback: force the month to land in the full `[min, max]` range
 * whenever legally possible. `belowMinFloor` (`runningBlockMinutesSoFar <
 * targetBlockMinutesMin`, recomputed every day) suppresses exactly the
 * PURELY-COSMETIC pacing/spacing preferences this generator itself invented
 * — never a legality check, and never the two heuristics that stand in for
 * an actual GCAA days-off floor:
 *
 *   - Layer 1's weekly block-budget filter (`filterCandidatesWithinWeeklyBudget`)
 *     is skipped while below the floor — its only purpose is stopping one
 *     week from absorbing several weeks' worth of budget, which is exactly
 *     what catching up on a floor needs to be allowed to do. The month-level
 *     `targetBlockMinutesMax` filter (`filterCandidatesWithinBudget`) is
 *     NEVER skipped — the hard ceiling stays hard regardless of the floor.
 *   - Layer 2's weekly-pacing OFF trigger (`forcedOffByWeeklyPacing`) and the
 *     natural-variation streak extension (`forcedOffByStreakExtension`, docs
 *     item 22) are both suppressed while below the floor — an in-progress
 *     weekly-pacing-triggered OFF streak is cut short and flying resumes the
 *     moment a legal, budget-eligible candidate exists again.
 *   - The multi-day-candidate weekly-slice-headroom guard inside the
 *     construction loop (`remainingDaysInSliceAfterCandidate <
 *     weeklyStillNeededOff`) is skipped for the same reason — it exists
 *     solely to protect layer 2's own trigger, which is itself suppressed.
 *
 * Deliberately NEVER suppressed while below the floor: `forcedOffByPacing`
 * (the month-level `TARGET_DAYS_OFF_PER_MONTH` check, approximating
 * ORO.FTL.205.G's real days-off-per-28-days floor) and
 * `forcedOffByConsecutiveCap` (margin below the real 7-consecutive-duty-day
 * ceiling) — both are this generator's proxies for an actual GCAA legal
 * minimum, not a cosmetic preference, so a block-hours floor never gets to
 * override them. Even without that guard, the per-candidate `evaluateDuty()`
 * RED screen remains the ultimate backstop: flying more days without
 * reaching a real days-off floor would eventually surface as a RED
 * evaluation and get rejected regardless. The floor is therefore always
 * best-effort — never a guarantee — exactly like the pre-existing ceiling
 * behavior it mirrors: if legality and the real days-off/duty-day floors
 * leave no room, the month can still land under `targetBlockMinutesMin`,
 * which remains an accepted outcome, never an error.
 *
 * CROSS-MONTH REST + CONSECUTIVE-DUTY-DAY CARRY-OVER
 * (docs/roster-gen-assumptions.md item 24): self-diagnosed gap, not a user
 * complaint — every check above only ever looks at THIS month's own `days`
 * array, so day 1 of any month was never rest-checked against the pilot's
 * real last duty of the previous month, and a consecutive-duty-day run
 * spanning the boundary was silently reset to 0. `input.priorMonthTailDays`
 * (optional; `undefined` reproduces today's behavior byte-for-byte) is the
 * previous calendar month's ACTUAL roster, used ONLY to:
 *
 *   - seed `evaluateRosterDays`'s `prevDutyEnd` from the last real FLIGHT
 *     day found in it (`findPriorMonthDutyEnd`), so day 1's minimum-rest
 *     check has real history instead of starting from nothing.
 *   - continue a consecutive-duty-day run into the new month
 *     (`countConsecutiveDutyDaysAtEndWithCarryOver`), so a run that ends
 *     the prior month still flying correctly counts toward both the
 *     construction loop's `forcedOffByConsecutiveCap`/`MAX_CONSECUTIVE_DUTY_DAYS`
 *     eligibility check (the site that actually PREVENTS an illegal day
 *     from ever being offered) and `evaluateRosterDays`'s own
 *     `cumulative.consecutiveDutyDays` (the final verification pass).
 *
 * DELIBERATELY NOT DONE: the 7/14/28-day trailing block/duty-minute sums
 * (`trailingSum`/`trailingCount` over this month's own `dailyBlockMinutes`/
 * `dailyDutyMinutes`/`isOff`) and the days-off-in-N-day window checks
 * (`gcaa-days-off-2-in-14`, `-7-in-28`, `-avg-8-per-28-over-3`) are NOT
 * extended by `priorMonthTailDays` — they stay scoped to the current
 * month only, and stay suppressed until day 14/28 of *this* month's own
 * history, exactly as before. Carrying those over would need up to 28 days
 * of prior daily arrays AND un-suppressing those checks from day 1 when
 * real history exists instead of only from day 14/28 — a materially
 * bigger change than this item makes. Documented here as a known,
 * intentional follow-on gap, not an oversight.
 *
 * SURFACING WHY AN OFF DAY HAPPENED (docs/roster-gen-assumptions.md item
 * 25, IN-MEMORY ONLY, never persisted): the construction loop below already
 * computes exactly which condition forced a given OFF day
 * (`forcedOffByPacing`/`forcedOffByConsecutiveCap`/`forcedOffByWeeklyPacing`/
 * `forcedOffByStreakExtension`, or none of those with no eligible candidate
 * either) — `determineOffReason` resolves this into `RosterGenDayAssignment`'s
 * OFF-variant `reason` field (optional; only this generator's own OFF days
 * ever set it — `src/roster-gen/db/loadRosterGenDays.ts` reconstructing an
 * OFF day from a persisted `RosterEntry` leaves it `undefined`, since it was
 * never persisted). `summary.offReasonCounts` tallies these for the caller.
 * Confirmed scope: this is a debugging/observability aid surfaced only in
 * the immediate post-generation summary UI (`actions.ts`'s `genSummary`) —
 * not a durable fact about the roster, so it is never written to
 * `RosterEntry` and never survives a page reload.
 */

import type { GeneratedPairing, PairingLegResult } from '../pairing/types';
import { computeDutyMinutes, computeReportTime } from '../pairing/dutyTimes';
import { toFlightDutyPeriod } from '../pairing/toFlightDutyPeriod';
import { evaluateDuty } from '../ftl/evaluate';
import type {
  CumulativeTotals,
  FlightDutyPeriod,
  OperatorSpecificOverrides,
  RestPeriodInput,
} from '../ftl/types';
import { classifyHaulType, type HaulType } from './haulType';
import type {
  DatedRuleEvaluation,
  GenerateMonthlyRosterInput,
  GenerationStrategy,
  MonthlyRosterGenerationResult,
  OffReason,
  RosterGenDay,
} from './types';

const HOME_BASE_IATA = 'DXB';

/** Soft trigger for a forced OFF day — margin below the legal 7-consecutive-duty-day ceiling (ORO.FTL.205.G). */
const CONSECUTIVE_DUTY_DAYS_SOFT_CAP = 6;
/** Hard ceiling this generator never exceeds (see module doc comment — the 8th-day exception is never invoked). */
const MAX_CONSECUTIVE_DUTY_DAYS = 7;
/** Target OFF days for the whole month, approximating ORO.FTL.205.G's ">=7 days off/28d" floor and ">=8/28d over 3 periods" average as one single-period goal (see docs/roster-gen-assumptions.md). */
const TARGET_DAYS_OFF_PER_MONTH = 8;
/** From this day of the month onward, bias remaining days toward OFF if the days-off pace is behind target. */
const PACING_CHECK_FROM_DAY = 24;
/** Sequential (not calendar-ISO) week-slice length for weekly pacing — see docs/roster-gen-assumptions.md item 21. */
const WEEK_SLICE_LENGTH_DAYS = 7;
/**
 * How far over its own soft weekly block-minutes slice a week is allowed to
 * run before a candidate is filtered out (docs item 21). 50% was chosen so a
 * single legitimately large pairing (this codebase's synthetic/real pairings
 * commonly run to ~1000-1700 block-min for a 3-4 day trip) can still be
 * absorbed by one week without permanently blocking that week's every
 * candidate, while still capping any one week to at most 1.5x an even
 * month-wide split — nowhere near enough to reproduce the diagnosed
 * whole-budget-in-2-weeks failure mode.
 */
const WEEKLY_BLOCK_TOLERANCE_FRACTION = 0.5;
/** See the module doc comment's "NATURAL OFF-BLOCK VARIATION" section (docs item 22) — max days the weekly-pacing trigger window may fire early. */
const WEEKLY_PACING_TRIGGER_SLACK_MAX_DAYS = 2;
/** See the module doc comment's "NATURAL OFF-BLOCK VARIATION" section (docs item 22) — max extra days a weekly-pacing-triggered OFF streak may continue beyond its mechanical minimum. */
const OFF_STREAK_EXTENSION_MAX_DAYS = 2;

function isoDate(year: number, month: number, day: number): string {
  return new Date(Date.UTC(year, month - 1, day)).toISOString().slice(0, 10);
}

function daysInMonthOf(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

// --- deterministic PRNG (mulberry32) — reproducible candidate-order shuffling ---
function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): void {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}

/**
 * Rolls one week slice's weekly-pacing trigger-window slack (0-2 days) —
 * see the module doc comment's "NATURAL OFF-BLOCK VARIATION" section (docs
 * item 22). Weighted toward 0/1 so most slices still trigger close to the
 * mechanical deadline, with a genuine chance of firing up to
 * `WEEKLY_PACING_TRIGGER_SLACK_MAX_DAYS` days earlier.
 */
function rollWeeklyPacingTriggerSlackDays(rng: () => number): number {
  const r = rng();
  if (r < 0.4) return 0;
  if (r < 0.75) return 1;
  return WEEKLY_PACING_TRIGGER_SLACK_MAX_DAYS;
}

/**
 * Rolls how many EXTRA days (0-2) a weekly-pacing-triggered OFF streak
 * continues beyond its mechanical minimum — see the module doc comment's
 * "NATURAL OFF-BLOCK VARIATION" section (docs item 22). 45% no extension
 * (the mechanical block stands as-is), 35% one extra day, 20% two extra
 * days — an expected extra of ~0.75 day stacked on top of whatever the
 * trigger's own mechanical minimum was, landing typical total block length
 * in the 2-4 day range without ever hard-capping it.
 */
function rollOffStreakExtensionDays(rng: () => number): number {
  const r = rng();
  if (r < 0.45) return 0;
  if (r < 0.8) return 1;
  return OFF_STREAK_EXTENSION_MAX_DAYS;
}

function countConsecutiveDutyDaysAtEnd(days: RosterGenDay[]): number {
  let count = 0;
  for (let i = days.length - 1; i >= 0; i -= 1) {
    if (days[i].assignment.type !== 'FLIGHT') break;
    count += 1;
  }
  return count;
}

/**
 * Docs item 24 — like `countConsecutiveDutyDaysAtEnd`, but a run that fills
 * the entirety of `days` continues counting into `priorMonthTailDays`'s own
 * trailing FLIGHT run. No change to `countConsecutiveDutyDaysAtEnd` itself
 * is needed: prepending is correct as-is, because the backward walk only
 * ever reaches into `priorMonthTailDays` when EVERY day of `days` is
 * itself FLIGHT — the moment it hits a non-FLIGHT day (in either array),
 * the walk stops exactly where it always did. `priorMonthTailDays` absent
 * degenerates to the plain call.
 */
function countConsecutiveDutyDaysAtEndWithCarryOver(
  days: RosterGenDay[],
  priorMonthTailDays: RosterGenDay[] | undefined
): number {
  if (!priorMonthTailDays || priorMonthTailDays.length === 0) {
    return countConsecutiveDutyDaysAtEnd(days);
  }
  return countConsecutiveDutyDaysAtEnd([...priorMonthTailDays, ...days]);
}


function buildCandidateDays(
  pairing: GeneratedPairing,
  dates: string[],
  startDayIndex0: number
): RosterGenDay[] {
  const out: RosterGenDay[] = [];
  for (let k = 0; k < pairing.tripDays; k += 1) {
    out.push({
      date: dates[startDayIndex0 + k],
      assignment: { type: 'FLIGHT', pairing, dayOfPairing: k + 1 },
    });
  }
  return out;
}

function trailingSum(arr: number[], endIndex: number, windowSize: number): number {
  const start = Math.max(0, endIndex - windowSize + 1);
  let sum = 0;
  for (let i = start; i <= endIndex; i += 1) sum += arr[i] ?? 0;
  return sum;
}

function trailingCount(flags: boolean[], endIndex: number, windowSize: number): number {
  const start = Math.max(0, endIndex - windowSize + 1);
  let count = 0;
  for (let i = start; i <= endIndex; i += 1) if (flags[i]) count += 1;
  return count;
}

function legsOnDay(pairing: GeneratedPairing, date: string): PairingLegResult[] {
  return pairing.legs
    .filter((leg) => leg.instance.serviceDate === date)
    .sort((a, b) => a.instance.depUTC.getTime() - b.instance.depUTC.getTime());
}

interface DailyArrays {
  dailyBlockMinutes: number[];
  dailyDutyMinutes: number[];
  isOff: boolean[];
}

function buildDailyArrays(days: RosterGenDay[]): DailyArrays {
  const n = days.length;
  const dailyBlockMinutes = new Array<number>(n).fill(0);
  const dailyDutyMinutes = new Array<number>(n).fill(0);
  const isOff = new Array<boolean>(n).fill(false);

  for (let i = 0; i < n; i += 1) {
    const day = days[i];
    if (day.assignment.type === 'OFF') {
      isOff[i] = true;
      continue;
    }
    const legs = legsOnDay(day.assignment.pairing, day.date);
    if (legs.length === 0) continue; // pure layover day within a multi-day pairing — occupies the day but flies nothing
    dailyBlockMinutes[i] = legs.reduce((sum, leg) => sum + leg.instance.blockTimeMin, 0);
    const reportUTC = computeReportTime(legs[0].instance.depUTC).reportUTC;
    const lastOnBlocksUTC = legs[legs.length - 1].instance.arrUTC;
    dailyDutyMinutes[i] = computeDutyMinutes(reportUTC, lastOnBlocksUTC);
  }

  return { dailyBlockMinutes, dailyDutyMinutes, isOff };
}

interface DutyEndInfo {
  utc: Date;
  minutes: number;
  station: string;
}

/**
 * The exact reportUTC/depAirportTz/`FlightDutyPeriod` computation a FLIGHT
 * day with real legs needs — extracted (docs item 24) from
 * `evaluateRosterDays`'s own per-day loop so it can be reused to inspect a
 * day OUTSIDE that loop too (`findPriorMonthDutyEnd` below). Pure
 * refactor — no behavior change to the loop itself. Returns `null` for an
 * OFF day or a pure layover day with no legs that date, exactly like the
 * loop's own `continue` conditions did inline.
 */
function computeFlightDayFdp(
  day: RosterGenDay,
  airportTimeZones: Record<string, string>
): { fdp: FlightDutyPeriod; reportUTC: Date; lastOnBlocksUTC: Date; arrIata: string } | null {
  if (day.assignment.type !== 'FLIGHT') return null;
  const legs = legsOnDay(day.assignment.pairing, day.date);
  if (legs.length === 0) return null;

  const depIata = legs[0].instance.depIata;
  const reportUTC = computeReportTime(legs[0].instance.depUTC).reportUTC;
  const lastOnBlocksUTC = legs[legs.length - 1].instance.arrUTC;

  const fdp = toFlightDutyPeriod({
    reportUTC,
    depAirportTz: airportTimeZones[depIata] ?? 'UTC',
    legs: legs.map((leg) => ({ blockTimeMin: leg.instance.blockTimeMin })),
    lastOnBlocksUTC,
    isAcclimatised: true,
  });

  return { fdp, reportUTC, lastOnBlocksUTC, arrIata: legs[legs.length - 1].instance.arrIata };
}

/**
 * Docs item 24 — the last real duty of `priorMonthTailDays` (the previous
 * calendar month's ACTUAL roster), in the same `{ utc, minutes, station }`
 * shape `evaluateRosterDays`'s own `prevDutyEnd` already uses, so day 1 of
 * the current month can be rest-checked against it instead of starting
 * with no history. `dailyDutyMinutes` (the same per-day fallback
 * `evaluateRosterDays` itself uses when `fdp.actualOrPlannedFdpMinutes` is
 * unset) is derived from `buildDailyArrays(priorMonthTailDays)` so this
 * mirrors the main loop's own computation exactly, not an approximation of
 * it. Returns `null` when `priorMonthTailDays` is absent/empty, or when no
 * FLIGHT day with real legs is found in it — the caller then behaves
 * exactly as if no prior-month data existed at all.
 */
function findPriorMonthDutyEnd(
  priorMonthTailDays: RosterGenDay[] | undefined,
  airportTimeZones: Record<string, string>
): DutyEndInfo | null {
  if (!priorMonthTailDays || priorMonthTailDays.length === 0) return null;

  const { dailyDutyMinutes } = buildDailyArrays(priorMonthTailDays);
  for (let i = priorMonthTailDays.length - 1; i >= 0; i -= 1) {
    const built = computeFlightDayFdp(priorMonthTailDays[i], airportTimeZones);
    if (!built) continue;
    return {
      utc: built.lastOnBlocksUTC,
      minutes: built.fdp.actualOrPlannedFdpMinutes ?? dailyDutyMinutes[i],
      station: built.arrIata,
    };
  }
  return null;
}

/**
 * Runs the real `src/ftl/evaluate.ts#evaluateDuty()` against every FLIGHT
 * day (with actual legs that day) in `days`, in chronological order,
 * rebuilding `FlightDutyPeriod`/`RestPeriodInput`/`CumulativeTotals` from
 * scratch from the day array alone (no reuse of any construction-time
 * bookkeeping) — this is both the construction-time candidate screen
 * (called on a tentative prefix+candidate array) and the final independent
 * verification pass (called once on the finished month).
 *
 * WINDOW-VALIDITY NOTE: `ORO.FTL.205.G`'s "days off in any N consecutive
 * days" checks (2-in-14, 7-in-28, and the 8-per-28-over-3-periods average)
 * are only meaningful once a full N-day window of *this roster's own
 * history* has elapsed — this generator has no prior-month data to fill a
 * partial window with, and a truncated window (e.g. "0 days off in the
 * first 3 days") is not a real violation, just an artifact of not enough
 * days having happened yet. Rather than fabricate history, those specific
 * sub-evaluations are omitted from the result until their window is full
 * (`gcaa-days-off-2-in-14` from day 14, `gcaa-days-off-7-in-28` and
 * `gcaa-days-off-avg-8-per-28-over-3` from day 28) — every other check
 * (FDP-table, minimum rest, the 8th-consecutive-duty-day / 7-day ceiling,
 * and the absolute block/duty-hour caps, which ARE meaningful against a
 * partial window since they are upper bounds, not floors) is always
 * surfaced. `avgDaysOffPer28dOver3Periods` is approximated by this single
 * period's own 28-day days-off count (documented limitation — a true
 * 3-period average needs 3 months of history).
 *
 * `priorMonthTailDays` (docs item 24) optionally seeds `prevDutyEnd` and the
 * consecutive-duty-day count from the previous calendar month's ACTUAL
 * roster — see the module doc comment's "CROSS-MONTH REST + CONSECUTIVE-
 * DUTY-DAY CARRY-OVER" section. `availableHistory14`/`availableHistory28`
 * and the days-off-in-N-day window suppression below are DELIBERATELY NOT
 * extended by it — see that same section for why.
 */
export function evaluateRosterDays(
  days: RosterGenDay[],
  airportTimeZones: Record<string, string>,
  operatorConfig?: OperatorSpecificOverrides,
  priorMonthTailDays?: RosterGenDay[]
): DatedRuleEvaluation[] {
  const { dailyBlockMinutes, dailyDutyMinutes, isOff } = buildDailyArrays(days);
  const results: DatedRuleEvaluation[] = [];

  let prevDutyEnd: DutyEndInfo | null = findPriorMonthDutyEnd(
    priorMonthTailDays,
    airportTimeZones
  );

  for (let i = 0; i < days.length; i += 1) {
    const day = days[i];
    const built = computeFlightDayFdp(day, airportTimeZones);
    if (!built) continue;
    const { fdp, reportUTC, lastOnBlocksUTC, arrIata } = built;

    let rest: RestPeriodInput | null = null;
    if (prevDutyEnd) {
      const gapMinutes = Math.max(
        0,
        Math.round((reportUTC.getTime() - prevDutyEnd.utc.getTime()) / 60_000)
      );
      rest = {
        precedingDutyMinutes: prevDutyEnd.minutes,
        role: 'FLIGHT_CREW',
        awayFromBase: prevDutyEnd.station !== HOME_BASE_IATA,
        earnedRestMinutes: gapMinutes,
      };
    }

    const availableHistory14 = i + 1;
    const availableHistory28 = i + 1;
    const consecutiveDutyDays = countConsecutiveDutyDaysAtEndWithCarryOver(
      days.slice(0, i + 1),
      priorMonthTailDays
    );

    const cumulative: CumulativeTotals = {
      blockMinutes28d: trailingSum(dailyBlockMinutes, i, 28),
      // See module doc comment: month-to-date total stands in for a true
      // 12-month rolling figure this single-month generator cannot compute.
      blockMinutes12mo: trailingSum(dailyBlockMinutes, i, days.length),
      dutyMinutes7d: trailingSum(dailyDutyMinutes, i, 7),
      dutyMinutes14d: trailingSum(dailyDutyMinutes, i, 14),
      dutyMinutes28d: trailingSum(dailyDutyMinutes, i, 28),
      consecutiveDutyDays,
      daysOffLast14: trailingCount(isOff, i, 14),
      daysOffLast28: trailingCount(isOff, i, 28),
      avgDaysOffPer28dOver3Periods: trailingCount(isOff, i, 28),
    };

    const dutyEvaluations = evaluateDuty(fdp, rest, cumulative, operatorConfig).filter((evaluation) => {
      const ruleId = evaluation.citation.ruleId;
      if (ruleId === 'gcaa-days-off-2-in-14' && availableHistory14 < 14) return false;
      if (ruleId === 'gcaa-days-off-7-in-28' && availableHistory28 < 28) return false;
      if (ruleId === 'gcaa-days-off-avg-8-per-28-over-3' && availableHistory28 < 28) return false;
      return true;
    });

    for (const evaluation of dutyEvaluations) {
      results.push({ date: day.date, evaluation });
    }

    prevDutyEnd = {
      utc: lastOnBlocksUTC,
      minutes: fdp.actualOrPlannedFdpMinutes ?? dailyDutyMinutes[i],
      station: arrIata,
    };
  }

  return results;
}

/** Total block minutes across every leg of one pairing. */
function pairingBlockMinutes(pairing: GeneratedPairing): number {
  return pairing.legs.reduce((sum, leg) => sum + leg.instance.blockTimeMin, 0);
}

function sumBlockMinutes(days: RosterGenDay[]): number {
  const seen = new Set<GeneratedPairing>();
  let total = 0;
  for (const day of days) {
    if (day.assignment.type === 'FLIGHT' && !seen.has(day.assignment.pairing)) {
      seen.add(day.assignment.pairing);
      total += pairingBlockMinutes(day.assignment.pairing);
    }
  }
  return total;
}

/**
 * Hard eligibility filter for the construction loop below, per
 * `GenerateMonthlyRosterInput.targetBlockMinutesMax`'s doc comment
 * (types.ts). Returns only the candidates that would NOT push the running
 * month-to-date block-minute total past `targetBlockMinutesMax` if
 * accepted. Returns `candidates` unchanged when `targetBlockMinutesMax` is
 * unset (no budget filtering at all). This runs BEFORE any strategy-based
 * ordering (`orderCandidatesByStrategy`) — eligibility is decided first,
 * preference is decided second, and this function never reorders anything
 * itself.
 */
function filterCandidatesWithinBudget(
  candidates: GeneratedPairing[],
  runningBlockMinutesSoFar: number,
  targetBlockMinutesMax: number | undefined
): GeneratedPairing[] {
  if (targetBlockMinutesMax == null) return candidates;
  return candidates.filter(
    (candidate) =>
      runningBlockMinutesSoFar + pairingBlockMinutes(candidate) <= targetBlockMinutesMax
  );
}

/** How many sequential 7-day-from-day-1 week slices a month divides into (docs item 21) — the last slice may be shorter than 7 days. */
function numberOfWeekSlices(daysInMonth: number): number {
  return Math.ceil(daysInMonth / WEEK_SLICE_LENGTH_DAYS);
}

/** 0-based [start0, end0] day-index bounds (inclusive) of the week slice containing `dayIndex0` (docs item 21). */
function weekSliceBoundsForDay(
  dayIndex0: number,
  daysInMonth: number
): { start0: number; end0: number } {
  const start0 = Math.floor(dayIndex0 / WEEK_SLICE_LENGTH_DAYS) * WEEK_SLICE_LENGTH_DAYS;
  const end0 = Math.min(daysInMonth - 1, start0 + WEEK_SLICE_LENGTH_DAYS - 1);
  return { start0, end0 };
}

/**
 * This week slice's own OFF-day target (docs item 21), scaled to the
 * slice's own length (`TARGET_DAYS_OFF_PER_MONTH * sliceLengthDays /
 * daysInMonth`, rounded) rather than a flat `TARGET_DAYS_OFF_PER_MONTH /
 * numberOfWeekSlices` split — a flat split would hold a short trailing
 * remainder slice (e.g. 2-3 days) to the same target as a full 7-day slice,
 * which for `TARGET_DAYS_OFF_PER_MONTH = 8` over ~5 slices rounds to 2 and
 * would force the ENTIRE remainder slice OFF regardless of legality or
 * budget headroom — clamped to `[0, sliceLengthDays]` as a final safety net
 * regardless of which formula is used.
 */
function targetOffDaysForWeekSlice(
  sliceLengthDays: number,
  daysInMonth: number
): number {
  const raw = Math.round((TARGET_DAYS_OFF_PER_MONTH * sliceLengthDays) / daysInMonth);
  return Math.max(0, Math.min(sliceLengthDays, raw));
}

/**
 * Additional (never a replacement for) weekly eligibility filter alongside
 * `filterCandidatesWithinBudget`, active only when `targetBlockMinutesMax`
 * is set (docs item 21). Returns only candidates that would not push the
 * CURRENT week slice's own running block-minute total past its soft slice
 * plus `WEEKLY_BLOCK_TOLERANCE_FRACTION` tolerance. `weeklyBlockSliceMinutes
 * === undefined` means no weekly budget filtering (mirrors
 * `filterCandidatesWithinBudget`'s own unset-ceiling behavior).
 *
 * EXCEPTION: when `weeklyBlockMinutesSoFar === 0` (nothing accepted in this
 * week slice yet), this filter is a no-op — the month-level filter above
 * remains the sole gate. Without this, a tight month-level budget spread
 * over several week slices can produce a weekly slice smaller than a single
 * real pairing's own block time (e.g. a 1400-min month ceiling over 5 weeks
 * is a 280-min/week slice, smaller than almost any real pairing), which
 * would incorrectly block even a week's very first, otherwise-legal pick —
 * starving the month of flying it could easily afford, not "pacing" it. The
 * whole point of weekly pacing is to stop one week from absorbing SEVERAL
 * pairings' worth of budget that other weeks then go without — it was never
 * meant to block a week's first pairing outright.
 */
function filterCandidatesWithinWeeklyBudget(
  candidates: GeneratedPairing[],
  weeklyBlockMinutesSoFar: number,
  weeklyBlockSliceMinutes: number | undefined
): GeneratedPairing[] {
  if (weeklyBlockSliceMinutes == null) return candidates;
  if (weeklyBlockMinutesSoFar === 0) return candidates;
  const weeklyCeiling = weeklyBlockSliceMinutes * (1 + WEEKLY_BLOCK_TOLERANCE_FRACTION);
  return candidates.filter(
    (candidate) => weeklyBlockMinutesSoFar + pairingBlockMinutes(candidate) <= weeklyCeiling
  );
}

/**
 * Orders one day's ALREADY-budget-filtered eligible candidates for the
 * construction loop below, per `input.generationStrategy`'s doc comment
 * (`GenerationStrategy` in types.ts). Always returns a NEW array
 * (Array#sort is stable, so candidates tied on the sort key keep their
 * existing deterministic-shuffle relative order — route variety among ties
 * is unaffected). Never mutates `candidates` itself, since the same
 * shuffled bucket array is looked up again if this date were ever
 * revisited.
 */
function orderCandidatesByStrategy(
  candidates: GeneratedPairing[],
  strategy: GenerationStrategy,
  haulTypeCountsSoFar: Record<HaulType, number>
): GeneratedPairing[] {
  if (strategy === 'MAX_FLYING') {
    return [...candidates].sort((a, b) => pairingBlockMinutes(a) - pairingBlockMinutes(b));
  }
  if (strategy === 'MAX_DAYS_OFF') {
    return [...candidates].sort((a, b) => pairingBlockMinutes(b) - pairingBlockMinutes(a));
  }
  // MIX (default): prefer whichever haul type is currently
  // least-represented among pairings assigned so far this month.
  return [...candidates].sort(
    (a, b) =>
      haulTypeCountsSoFar[classifyHaulType(a)] - haulTypeCountsSoFar[classifyHaulType(b)]
  );
}

function countDistinctPairings(days: RosterGenDay[]): number {
  const seen = new Set<GeneratedPairing>();
  for (const day of days) {
    if (day.assignment.type === 'FLIGHT') seen.add(day.assignment.pairing);
  }
  return seen.size;
}

/**
 * Docs item 25 — resolves WHY a forced OFF day happened, in the exact same
 * precedence order as the construction loop's own gate below (`if
 * (!forcedOffByPacing && !forcedOffByConsecutiveCap && !forcedOffByWeeklyPacing
 * && !forcedOffByStreakExtension)`): first true wins. If none of the four
 * forced it but the day still went OFF, no legal/budget-eligible candidate
 * existed for it — see `OffReason`'s own doc comment (types.ts).
 */
function determineOffReason(
  forcedOffByPacing: boolean,
  forcedOffByConsecutiveCap: boolean,
  forcedOffByWeeklyPacing: boolean,
  forcedOffByStreakExtension: boolean
): OffReason {
  if (forcedOffByPacing) return 'MONTH_PACING';
  if (forcedOffByConsecutiveCap) return 'CONSECUTIVE_CAP';
  if (forcedOffByWeeklyPacing) return 'WEEKLY_PACING';
  if (forcedOffByStreakExtension) return 'STREAK_EXTENSION';
  return 'NO_ELIGIBLE_CANDIDATE';
}

/** Tallies every OFF day's `reason` (docs item 25) — every key present, sums to the number of OFF days with a reason. */
function computeOffReasonCounts(days: RosterGenDay[]): Record<OffReason, number> {
  const counts: Record<OffReason, number> = {
    MONTH_PACING: 0,
    CONSECUTIVE_CAP: 0,
    WEEKLY_PACING: 0,
    STREAK_EXTENSION: 0,
    NO_ELIGIBLE_CANDIDATE: 0,
  };
  for (const day of days) {
    if (day.assignment.type === 'OFF' && day.assignment.reason) {
      counts[day.assignment.reason] += 1;
    }
  }
  return counts;
}

/**
 * Generates a full-month FLIGHT/OFF assignment for one fleet type. Pure
 * function — see this module's doc comment for the algorithm and its
 * explicit scope limitations.
 */
export function generateMonthlyRoster(
  input: GenerateMonthlyRosterInput
): MonthlyRosterGenerationResult {
  const {
    fleetType,
    year,
    month,
    pairings,
    airportTimeZones,
    operatorConfig,
    targetBlockMinutesMin,
    targetBlockMinutesMax,
    generationStrategy = 'MIX',
    priorMonthTailDays,
  } = input;

  const daysInMonth = daysInMonthOf(year, month);
  const dates = Array.from({ length: daysInMonth }, (_, i) => isoDate(year, month, i + 1));

  const candidatesByStart = new Map<string, GeneratedPairing[]>();
  for (const pairing of pairings) {
    const bucket = candidatesByStart.get(pairing.startServiceDate) ?? [];
    bucket.push(pairing);
    candidatesByStart.set(pairing.startServiceDate, bucket);
  }

  const rng = mulberry32(hashSeed(`${fleetType}|${year}|${month}`));
  for (const bucket of candidatesByStart.values()) {
    shuffleInPlace(bucket, rng);
  }
  // Separate seeded stream for the weekly-pacing natural-variation knobs
  // (docs item 22) — kept independent of `rng` above so adding/removing
  // either concern never perturbs the other's draw sequence, while both
  // stay fully deterministic per fleet/year/month.
  const weeklyPacingVariationRng = mulberry32(
    hashSeed(`${fleetType}|${year}|${month}|weekly-pacing-variation`)
  );

  const days: RosterGenDay[] = [];
  let dayIndex0 = 0; // 0-based cursor
  let daysOffSoFar = 0;
  let runningBlockMinutesSoFar = 0;
  const haulTypeCountsSoFar: Record<HaulType, number> = { SHORT: 0, MEDIUM: 0, LONG: 0 };

  const numSlices = numberOfWeekSlices(daysInMonth);
  const weeklyBlockSliceMinutes =
    targetBlockMinutesMax == null ? undefined : targetBlockMinutesMax / numSlices;
  let currentWeekSliceStart0 = -1; // sentinel — forces a reset on the first iteration
  let weeklyBlockMinutesSoFar = 0;
  let weeklyOffDaysSoFar = 0;
  // Natural OFF-block variation state (docs item 22) — see the module doc
  // comment's "NATURAL OFF-BLOCK VARIATION" section. `sliceTriggerSlackDays`
  // is re-rolled once per week slice; `offStreakExtensionRemainingDays` is
  // rolled once per fresh weekly-pacing-triggered OFF streak and decremented
  // while it runs.
  let sliceTriggerSlackDays = 0;
  let offStreakExtensionRemainingDays = 0;

  while (dayIndex0 < daysInMonth) {
    const date = dates[dayIndex0];
    const consecutiveDutyDaysBefore = countConsecutiveDutyDaysAtEndWithCarryOver(
      days,
      priorMonthTailDays
    );
    const remainingDaysInMonth = daysInMonth - dayIndex0;
    const priorDayType = days.length > 0 ? days[days.length - 1].assignment.type : null;
    const isFreshOffStreakStart = priorDayType !== 'FLIGHT';

    const { start0: sliceStart0, end0: sliceEnd0 } = weekSliceBoundsForDay(dayIndex0, daysInMonth);
    if (sliceStart0 !== currentWeekSliceStart0) {
      currentWeekSliceStart0 = sliceStart0;
      weeklyBlockMinutesSoFar = 0;
      weeklyOffDaysSoFar = 0;
      sliceTriggerSlackDays = rollWeeklyPacingTriggerSlackDays(weeklyPacingVariationRng);
    }
    const sliceLengthDays = sliceEnd0 - sliceStart0 + 1;
    const remainingDaysInSlice = sliceEnd0 - dayIndex0 + 1;
    const weeklyTargetOffDays = targetOffDaysForWeekSlice(sliceLengthDays, daysInMonth);
    const weeklyStillNeededOff = Math.max(0, weeklyTargetOffDays - weeklyOffDaysSoFar);
    // Slack only ever pulls an ALREADY-still-needed trigger earlier
    // (`weeklyStillNeededOff > 0` guard) — see the module doc comment for
    // why this guard is required (docs item 22).
    // Enforced min block-hours floor (docs item 23) — see the module doc
    // comment's "ENFORCED MIN BLOCK-HOURS FLOOR" section. Suppresses only
    // this generator's own cosmetic pacing/spacing heuristics (layer 1's
    // weekly budget filter, layer 2's trigger, and item 22's streak
    // extension) — never `forcedOffByPacing`/`forcedOffByConsecutiveCap`
    // (this generator's proxies for a real GCAA days-off/duty-day floor)
    // and never any `evaluateDuty()` legality screen.
    const belowMinFloor =
      targetBlockMinutesMin != null && runningBlockMinutesSoFar < targetBlockMinutesMin;

    const forcedOffByWeeklyPacing =
      !belowMinFloor &&
      weeklyStillNeededOff > 0 &&
      weeklyStillNeededOff >= remainingDaysInSlice - sliceTriggerSlackDays;
    const forcedOffByStreakExtension = !belowMinFloor && offStreakExtensionRemainingDays > 0;

    const stillNeeded = Math.max(0, TARGET_DAYS_OFF_PER_MONTH - daysOffSoFar);
    const forcedOffByPacing =
      dayIndex0 + 1 >= PACING_CHECK_FROM_DAY && stillNeeded >= remainingDaysInMonth;
    const forcedOffByConsecutiveCap =
      consecutiveDutyDaysBefore >= CONSECUTIVE_DUTY_DAYS_SOFT_CAP;

    let assignedPairing: GeneratedPairing | null = null;

    if (
      !forcedOffByPacing &&
      !forcedOffByConsecutiveCap &&
      !forcedOffByWeeklyPacing &&
      !forcedOffByStreakExtension
    ) {
      const candidates = candidatesByStart.get(date) ?? [];
      const monthBudgetFiltered = filterCandidatesWithinBudget(
        candidates,
        runningBlockMinutesSoFar,
        targetBlockMinutesMax
      );
      const eligibleCandidates = filterCandidatesWithinWeeklyBudget(
        monthBudgetFiltered,
        weeklyBlockMinutesSoFar,
        belowMinFloor ? undefined : weeklyBlockSliceMinutes
      );
      const orderedCandidates = orderCandidatesByStrategy(
        eligibleCandidates,
        generationStrategy,
        haulTypeCountsSoFar
      );
      for (const candidate of orderedCandidates) {
        if (dayIndex0 + candidate.tripDays > daysInMonth) continue; // wouldn't fit in the month
        if (consecutiveDutyDaysBefore + candidate.tripDays > MAX_CONSECUTIVE_DUTY_DAYS) continue;
        // Would this multi-day candidate itself consume enough of the
        // CURRENT week slice's remaining days that the slice's own
        // days-off target becomes unreachable afterward? Without this
        // guard, a pairing accepted here could span straight past the
        // single day where `forcedOffByWeeklyPacing` would otherwise have
        // fired later this same slice — the day-level check above only
        // ever runs at whichever day the loop's cursor actually lands on,
        // and a multi-day pairing's own span is never individually
        // revisited (docs item 21).
        const remainingDaysInSliceAfterCandidate = Math.max(
          0,
          remainingDaysInSlice - candidate.tripDays
        );
        if (!belowMinFloor && remainingDaysInSliceAfterCandidate < weeklyStillNeededOff) continue;

        const candidateDays = buildCandidateDays(candidate, dates, dayIndex0);
        const hypothetical = [...days, ...candidateDays];
        const candidateDates = new Set(candidateDays.map((d) => d.date));
        const evaluations = evaluateRosterDays(
          hypothetical,
          airportTimeZones,
          operatorConfig,
          priorMonthTailDays
        );
        const hasRed = evaluations.some(
          (e) => candidateDates.has(e.date) && e.evaluation.severity === 'RED'
        );

        if (!hasRed) {
          assignedPairing = candidate;
          days.push(...candidateDays);
          dayIndex0 += candidate.tripDays;
          runningBlockMinutesSoFar += pairingBlockMinutes(candidate);
          weeklyBlockMinutesSoFar += pairingBlockMinutes(candidate);
          haulTypeCountsSoFar[classifyHaulType(candidate)] += 1;
          offStreakExtensionRemainingDays = 0; // flying resumed — any active streak ends
          break;
        }
      }
    }

    if (!assignedPairing) {
      const offReason = determineOffReason(
        forcedOffByPacing,
        forcedOffByConsecutiveCap,
        forcedOffByWeeklyPacing,
        forcedOffByStreakExtension
      );
      days.push({ date, assignment: { type: 'OFF', reason: offReason } });
      daysOffSoFar += 1;
      weeklyOffDaysSoFar += 1;
      dayIndex0 += 1;

      // Natural OFF-block variation (docs item 22) — see the module doc
      // comment. Only a FRESH streak caused specifically by the weekly
      // pacing trigger gets a length-extension roll; a streak already in
      // progress just decrements, and a streak caused by anything else
      // (month-level pacing, the consecutive-duty cap, or budget/legality
      // exhaustion) is left completely alone.
      if (isFreshOffStreakStart) {
        offStreakExtensionRemainingDays = forcedOffByWeeklyPacing
          ? rollOffStreakExtensionDays(weeklyPacingVariationRng)
          : 0;
      } else if (offStreakExtensionRemainingDays > 0) {
        offStreakExtensionRemainingDays -= 1;
      }
    }
  }

  const evaluations = evaluateRosterDays(
    days,
    airportTimeZones,
    operatorConfig,
    priorMonthTailDays
  );
  const flightDays = days.filter((d) => d.assignment.type === 'FLIGHT').length;

  return {
    fleetType,
    year,
    month,
    days,
    evaluations,
    summary: {
      flightDays,
      offDays: days.length - flightDays,
      totalBlockMinutes: sumBlockMinutes(days),
      pairingsAssigned: countDistinctPairings(days),
      offReasonCounts: computeOffReasonCounts(days),
    },
  };
}
