/**
 * Phase 4 — automatic monthly roster generator.
 *
 * Given a fleet type and a pool of candidate pairings for one calendar
 * month (already generated by Phase 2's `generatePairings`, filtered to
 * that fleet), produces a full day-by-day FLIGHT/OFF assignment for the
 * whole month, provably GCAA-compliant *by construction* (every candidate
 * is screened against the real Phase 3 evaluator before being accepted),
 * plus an independent post-generation verification pass that re-runs
 * `evaluateDuty()` against the finished result.
 *
 * SCOPE (see docs/roster-gen-assumptions.md for the full list): this is a
 * personal-tool, single-month, greedy day-by-day generator — not a global
 * optimizer, and not a full CSP solver. It explicitly does NOT:
 *   - account for the 12-month rolling cumulative limits (900h/12mo block
 *     time) — this tool has no prior-month history to compute a real
 *     rolling 12-month figure from. `CumulativeTotals.blockMinutes12mo` is
 *     filled with this month's own running total as a documented stand-in
 *     (always far below the 900h ceiling for a single month, so this never
 *     produces a false RED — it just isn't a real cross-month check).
 *   - model any Emirates-specific FTL Variation / augmented-crew scheme
 *     (consistent with Phase 3's own `OPERATOR_SPECIFIC` marking in
 *     `src/ftl/rules/operatorSpecific.ts`).
 *   - try to be globally optimal (maximize pay, minimize fatigue beyond the
 *     hard legal floor, etc.) — it produces *a* compliant roster, not *the
 *     best* one.
 *   - track real acclimatisation history (`src/ftl/rules/acclimatisation.ts`
 *     needs consecutive-local-night history this generator doesn't keep);
 *     every duty is assumed `isAcclimatised: true` (Table A limits), a
 *     simplification applied identically during both construction-time
 *     screening and the final verification pass, so it cannot itself cause
 *     construction/verification disagreement.
 *   - assume anything about the crew member's rest state before day 1 of
 *     the month (no prior-month history) — the very first duty of the
 *     month is never rest-checked against a "previous" duty.
 *
 * ALGORITHM: greedy day-by-day walk (see module functions below). At each
 * unoccupied day, candidate pairings starting that day are tried (in a
 * deterministically shuffled order, for route variety) and accepted the
 * moment one is found that (a) fits in the remaining days of the month,
 * (b) keeps `consecutiveDutyDays` at or below 7, and (c) produces zero RED
 * `RuleEvaluation`s when the *real* `evaluateDuty()` is run against every
 * day it would occupy (FDP-table, minimum rest, and the cumulative
 * block/duty-hour ceilings). If no candidate fits, the day is OFF.
 *
 * HARD BLOCK-HOURS TARGET RANGE + SELECTABLE STRATEGY: when
 * `input.targetBlockMinutesMax` is set, it is enforced as a HARD
 * eligibility filter (see `filterCandidatesWithinBudget`), applied BEFORE
 * any ordering: a candidate is only eligible for a day if
 * `runningBlockMinutesSoFar + candidateBlockMinutes <=
 * targetBlockMinutesMax`. If no candidate is eligible (illegal, doesn't
 * fit the remaining month, or doesn't fit the remaining budget), the day is
 * OFF — this can leave the month under `targetBlockMinutesMin` at month
 * end, which is an accepted outcome, never an error (per explicit user
 * priority: prefer an OFF day over exceeding the ceiling).
 * `targetBlockMinutesMin` itself is NOT enforced as a filter — it is
 * informational only.
 *
 * Among the day's already-budget-filtered eligible candidates,
 * `input.generationStrategy` (default `'MIX'`) picks which one is tried
 * first (see `orderCandidatesByStrategy` and `GenerationStrategy`'s doc
 * comment in types.ts): `MIX` prefers the haul type
 * (`haulType.ts#classifyHaulType`) least-represented among pairings
 * assigned so far this month; `MAX_FLYING` prefers the smaller block-time
 * candidate (more distinct flying days for the same budget); `MAX_DAYS_OFF`
 * prefers the bigger block-time candidate (fewer trips, more days off).
 * This never changes (a)/(b)/(c) above — the budget filter and strategy
 * ordering only narrow/reorder which already-legal candidate is tried
 * first among the day's eligible options. See
 * docs/roster-gen-assumptions.md item 20 (item 19, preserved for history,
 * describes the prior soft-bias design this replaces).
 * `consecutiveDutyDays >= 6` pre-emptively forces an OFF day (margin below
 * the legal 7-day ceiling), and from day 24 onward an OFF day is forced
 * whenever the days-off pace could not otherwise reach the
 * `TARGET_DAYS_OFF_PER_MONTH` target by month end (see
 * `evaluateRosterDays` for why the "days off in any N days" checks are
 * suppressed until a full N-day window of *this* roster has elapsed —
 * they are not well-defined against a partial window with no prior-month
 * history, and this generator does not fabricate one).
 *
 * WEEKLY-BLOCK PACING (docs/roster-gen-assumptions.md item 21, extending
 * items 3 and 20): the month-level checks above are necessary but not
 * sufficient — a purely day-by-day greedy walk can legally spend the ENTIRE
 * `targetBlockMinutesMax` budget in the first 2-3 weeks (nothing above stops
 * it), forcing every remaining day of the month OFF as one giant tail once
 * the budget runs out. This was diagnosed against the user's real live
 * October 2026 roster (10 consecutive OFF days at the end of the month) and
 * is fixed by two ADDITIONAL, narrower eligibility/pacing layers, both
 * scoped to simple sequential 7-day-from-day-1 "week slices" (NOT calendar
 * ISO weeks — see `numberOfWeekSlices`/`weekSliceBoundsForDay`):
 *
 *   1. When `targetBlockMinutesMax` is set, each week slice additionally
 *      gets its own soft block-minutes slice (`targetBlockMinutesMax /
 *      numberOfWeekSlices`, flat division) plus a 50% tolerance
 *      (`WEEKLY_BLOCK_TOLERANCE_FRACTION`) — see
 *      `filterCandidatesWithinWeeklyBudget`. This runs BESIDE (never
 *      instead of) the existing month-level `filterCandidatesWithinBudget`;
 *      a candidate must pass BOTH.
 *   2. Independent of `targetBlockMinutesMax`, each week slice also gets its
 *      own OFF-day target (`TARGET_DAYS_OFF_PER_MONTH` scaled to the
 *      slice's own length, so a short trailing remainder slice isn't held to
 *      a full week's target) — see `targetOffDaysForWeekSlice`. Exactly like
 *      the existing month-level `PACING_CHECK_FROM_DAY` check, this forces
 *      OFF as soon as it becomes mathematically necessary to still hit that
 *      slice's own target before the slice ends, not only on the slice's
 *      literal last day.
 *
 * Both layers only ever narrow eligibility or force OFF sooner — they never
 * turn an illegal candidate legal, and they stack with (never replace) every
 * check above: a day goes OFF if ANY forcing condition or empty-eligible-set
 * condition says so.
 */

import type { GeneratedPairing, PairingLegResult } from '../pairing/types';
import { computeDutyMinutes, computeReportTime } from '../pairing/dutyTimes';
import { toFlightDutyPeriod } from '../pairing/toFlightDutyPeriod';
import { evaluateDuty } from '../ftl/evaluate';
import type { CumulativeTotals, OperatorSpecificOverrides, RestPeriodInput } from '../ftl/types';
import { classifyHaulType, type HaulType } from './haulType';
import type {
  DatedRuleEvaluation,
  GenerateMonthlyRosterInput,
  GenerationStrategy,
  MonthlyRosterGenerationResult,
  RosterGenDay,
} from './types';

const HOME_BASE_IATA = 'DXB';

/** Soft trigger for a forced OFF day — margin below the legal 7-consecutive-duty-day ceiling (ORO.FTL.205.G). */
const CONSECUTIVE_DUTY_DAYS_SOFT_CAP = 6;
/** Hard ceiling this generator never exceeds (see module doc comment — the 8th-day exception is never invoked). */
const MAX_CONSECUTIVE_DUTY_DAYS = 7;
/** Target OFF days for the whole month, approximating ORO.FTL.205.G's ">=7 days off/28d" floor and ">=8/28d over 3 periods" average as one single-period goal (see docs/roster-gen-assumptions.md). */
const TARGET_DAYS_OFF_PER_MONTH = 8;
/** From this day of the month onward, bias remaining days toward OFF if the days-off pace is behind target. */
const PACING_CHECK_FROM_DAY = 24;
/** Sequential (not calendar-ISO) week-slice length for weekly pacing — see docs/roster-gen-assumptions.md item 21. */
const WEEK_SLICE_LENGTH_DAYS = 7;
/**
 * How far over its own soft weekly block-minutes slice a week is allowed to
 * run before a candidate is filtered out (docs item 21). 50% was chosen so a
 * single legitimately large pairing (this codebase's synthetic/real pairings
 * commonly run to ~1000-1700 block-min for a 3-4 day trip) can still be
 * absorbed by one week without permanently blocking that week's every
 * candidate, while still capping any one week to at most 1.5x an even
 * month-wide split — nowhere near enough to reproduce the diagnosed
 * whole-budget-in-2-weeks failure mode.
 */
const WEEKLY_BLOCK_TOLERANCE_FRACTION = 0.5;

function isoDate(year: number, month: number, day: number): string {
  return new Date(Date.UTC(year, month - 1, day)).toISOString().slice(0, 10);
}

function daysInMonthOf(year: number, month: number): number {
  return new Date(Date.UTC(year, month, 0)).getUTCDate();
}

// --- deterministic PRNG (mulberry32) — reproducible candidate-order shuffling ---
function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): void {
  for (let i = arr.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
}

function countConsecutiveDutyDaysAtEnd(days: RosterGenDay[]): number {
  let count = 0;
  for (let i = days.length - 1; i >= 0; i -= 1) {
    if (days[i].assignment.type !== 'FLIGHT') break;
    count += 1;
  }
  return count;
}

function buildCandidateDays(
  pairing: GeneratedPairing,
  dates: string[],
  startDayIndex0: number
): RosterGenDay[] {
  const out: RosterGenDay[] = [];
  for (let k = 0; k < pairing.tripDays; k += 1) {
    out.push({
      date: dates[startDayIndex0 + k],
      assignment: { type: 'FLIGHT', pairing, dayOfPairing: k + 1 },
    });
  }
  return out;
}

function trailingSum(arr: number[], endIndex: number, windowSize: number): number {
  const start = Math.max(0, endIndex - windowSize + 1);
  let sum = 0;
  for (let i = start; i <= endIndex; i += 1) sum += arr[i] ?? 0;
  return sum;
}

function trailingCount(flags: boolean[], endIndex: number, windowSize: number): number {
  const start = Math.max(0, endIndex - windowSize + 1);
  let count = 0;
  for (let i = start; i <= endIndex; i += 1) if (flags[i]) count += 1;
  return count;
}

function legsOnDay(pairing: GeneratedPairing, date: string): PairingLegResult[] {
  return pairing.legs
    .filter((leg) => leg.instance.serviceDate === date)
    .sort((a, b) => a.instance.depUTC.getTime() - b.instance.depUTC.getTime());
}

interface DailyArrays {
  dailyBlockMinutes: number[];
  dailyDutyMinutes: number[];
  isOff: boolean[];
}

function buildDailyArrays(days: RosterGenDay[]): DailyArrays {
  const n = days.length;
  const dailyBlockMinutes = new Array<number>(n).fill(0);
  const dailyDutyMinutes = new Array<number>(n).fill(0);
  const isOff = new Array<boolean>(n).fill(false);

  for (let i = 0; i < n; i += 1) {
    const day = days[i];
    if (day.assignment.type === 'OFF') {
      isOff[i] = true;
      continue;
    }
    const legs = legsOnDay(day.assignment.pairing, day.date);
    if (legs.length === 0) continue; // pure layover day within a multi-day pairing — occupies the day but flies nothing
    dailyBlockMinutes[i] = legs.reduce((sum, leg) => sum + leg.instance.blockTimeMin, 0);
    const reportUTC = computeReportTime(legs[0].instance.depUTC).reportUTC;
    const lastOnBlocksUTC = legs[legs.length - 1].instance.arrUTC;
    dailyDutyMinutes[i] = computeDutyMinutes(reportUTC, lastOnBlocksUTC);
  }

  return { dailyBlockMinutes, dailyDutyMinutes, isOff };
}

/**
 * Runs the real `src/ftl/evaluate.ts#evaluateDuty()` against every FLIGHT
 * day (with actual legs that day) in `days`, in chronological order,
 * rebuilding `FlightDutyPeriod`/`RestPeriodInput`/`CumulativeTotals` from
 * scratch from the day array alone (no reuse of any construction-time
 * bookkeeping) — this is both the construction-time candidate screen
 * (called on a tentative prefix+candidate array) and the final independent
 * verification pass (called once on the finished month).
 *
 * WINDOW-VALIDITY NOTE: `ORO.FTL.205.G`'s "days off in any N consecutive
 * days" checks (2-in-14, 7-in-28, and the 8-per-28-over-3-periods average)
 * are only meaningful once a full N-day window of *this roster's own
 * history* has elapsed — this generator has no prior-month data to fill a
 * partial window with, and a truncated window (e.g. "0 days off in the
 * first 3 days") is not a real violation, just an artifact of not enough
 * days having happened yet. Rather than fabricate history, those specific
 * sub-evaluations are omitted from the result until their window is full
 * (`gcaa-days-off-2-in-14` from day 14, `gcaa-days-off-7-in-28` and
 * `gcaa-days-off-avg-8-per-28-over-3` from day 28) — every other check
 * (FDP-table, minimum rest, the 8th-consecutive-duty-day / 7-day ceiling,
 * and the absolute block/duty-hour caps, which ARE meaningful against a
 * partial window since they are upper bounds, not floors) is always
 * surfaced. `avgDaysOffPer28dOver3Periods` is approximated by this single
 * period's own 28-day days-off count (documented limitation — a true
 * 3-period average needs 3 months of history).
 */
export function evaluateRosterDays(
  days: RosterGenDay[],
  airportTimeZones: Record<string, string>,
  operatorConfig?: OperatorSpecificOverrides
): DatedRuleEvaluation[] {
  const { dailyBlockMinutes, dailyDutyMinutes, isOff } = buildDailyArrays(days);
  const results: DatedRuleEvaluation[] = [];

  let prevDutyEnd: { utc: Date; minutes: number; station: string } | null = null;

  for (let i = 0; i < days.length; i += 1) {
    const day = days[i];
    if (day.assignment.type !== 'FLIGHT') continue;

    const legs = legsOnDay(day.assignment.pairing, day.date);
    if (legs.length === 0) continue; // pure layover day, nothing to evaluate

    const depIata = legs[0].instance.depIata;
    const reportUTC = computeReportTime(legs[0].instance.depUTC).reportUTC;
    const lastOnBlocksUTC = legs[legs.length - 1].instance.arrUTC;

    const fdp = toFlightDutyPeriod({
      reportUTC,
      depAirportTz: airportTimeZones[depIata] ?? 'UTC',
      legs: legs.map((leg) => ({ blockTimeMin: leg.instance.blockTimeMin })),
      lastOnBlocksUTC,
      isAcclimatised: true,
    });

    let rest: RestPeriodInput | null = null;
    if (prevDutyEnd) {
      const gapMinutes = Math.max(
        0,
        Math.round((reportUTC.getTime() - prevDutyEnd.utc.getTime()) / 60_000)
      );
      rest = {
        precedingDutyMinutes: prevDutyEnd.minutes,
        role: 'FLIGHT_CREW',
        awayFromBase: prevDutyEnd.station !== HOME_BASE_IATA,
        earnedRestMinutes: gapMinutes,
      };
    }

    const availableHistory14 = i + 1;
    const availableHistory28 = i + 1;
    const consecutiveDutyDays = countConsecutiveDutyDaysAtEnd(days.slice(0, i + 1));

    const cumulative: CumulativeTotals = {
      blockMinutes28d: trailingSum(dailyBlockMinutes, i, 28),
      // See module doc comment: month-to-date total stands in for a true
      // 12-month rolling figure this single-month generator cannot compute.
      blockMinutes12mo: trailingSum(dailyBlockMinutes, i, days.length),
      dutyMinutes7d: trailingSum(dailyDutyMinutes, i, 7),
      dutyMinutes14d: trailingSum(dailyDutyMinutes, i, 14),
      dutyMinutes28d: trailingSum(dailyDutyMinutes, i, 28),
      consecutiveDutyDays,
      daysOffLast14: trailingCount(isOff, i, 14),
      daysOffLast28: trailingCount(isOff, i, 28),
      avgDaysOffPer28dOver3Periods: trailingCount(isOff, i, 28),
    };

    const dutyEvaluations = evaluateDuty(fdp, rest, cumulative, operatorConfig).filter((evaluation) => {
      const ruleId = evaluation.citation.ruleId;
      if (ruleId === 'gcaa-days-off-2-in-14' && availableHistory14 < 14) return false;
      if (ruleId === 'gcaa-days-off-7-in-28' && availableHistory28 < 28) return false;
      if (ruleId === 'gcaa-days-off-avg-8-per-28-over-3' && availableHistory28 < 28) return false;
      return true;
    });

    for (const evaluation of dutyEvaluations) {
      results.push({ date: day.date, evaluation });
    }

    prevDutyEnd = {
      utc: lastOnBlocksUTC,
      minutes: fdp.actualOrPlannedFdpMinutes ?? dailyDutyMinutes[i],
      station: legs[legs.length - 1].instance.arrIata,
    };
  }

  return results;
}

/** Total block minutes across every leg of one pairing. */
function pairingBlockMinutes(pairing: GeneratedPairing): number {
  return pairing.legs.reduce((sum, leg) => sum + leg.instance.blockTimeMin, 0);
}

function sumBlockMinutes(days: RosterGenDay[]): number {
  const seen = new Set<GeneratedPairing>();
  let total = 0;
  for (const day of days) {
    if (day.assignment.type === 'FLIGHT' && !seen.has(day.assignment.pairing)) {
      seen.add(day.assignment.pairing);
      total += pairingBlockMinutes(day.assignment.pairing);
    }
  }
  return total;
}

/**
 * Hard eligibility filter for the construction loop below, per
 * `GenerateMonthlyRosterInput.targetBlockMinutesMax`'s doc comment
 * (types.ts). Returns only the candidates that would NOT push the running
 * month-to-date block-minute total past `targetBlockMinutesMax` if
 * accepted. Returns `candidates` unchanged when `targetBlockMinutesMax` is
 * unset (no budget filtering at all). This runs BEFORE any strategy-based
 * ordering (`orderCandidatesByStrategy`) — eligibility is decided first,
 * preference is decided second, and this function never reorders anything
 * itself.
 */
function filterCandidatesWithinBudget(
  candidates: GeneratedPairing[],
  runningBlockMinutesSoFar: number,
  targetBlockMinutesMax: number | undefined
): GeneratedPairing[] {
  if (targetBlockMinutesMax == null) return candidates;
  return candidates.filter(
    (candidate) =>
      runningBlockMinutesSoFar + pairingBlockMinutes(candidate) <= targetBlockMinutesMax
  );
}

/** How many sequential 7-day-from-day-1 week slices a month divides into (docs item 21) — the last slice may be shorter than 7 days. */
function numberOfWeekSlices(daysInMonth: number): number {
  return Math.ceil(daysInMonth / WEEK_SLICE_LENGTH_DAYS);
}

/** 0-based [start0, end0] day-index bounds (inclusive) of the week slice containing `dayIndex0` (docs item 21). */
function weekSliceBoundsForDay(
  dayIndex0: number,
  daysInMonth: number
): { start0: number; end0: number } {
  const start0 = Math.floor(dayIndex0 / WEEK_SLICE_LENGTH_DAYS) * WEEK_SLICE_LENGTH_DAYS;
  const end0 = Math.min(daysInMonth - 1, start0 + WEEK_SLICE_LENGTH_DAYS - 1);
  return { start0, end0 };
}

/**
 * This week slice's own OFF-day target (docs item 21), scaled to the
 * slice's own length (`TARGET_DAYS_OFF_PER_MONTH * sliceLengthDays /
 * daysInMonth`, rounded) rather than a flat `TARGET_DAYS_OFF_PER_MONTH /
 * numberOfWeekSlices` split — a flat split would hold a short trailing
 * remainder slice (e.g. 2-3 days) to the same target as a full 7-day slice,
 * which for `TARGET_DAYS_OFF_PER_MONTH = 8` over ~5 slices rounds to 2 and
 * would force the ENTIRE remainder slice OFF regardless of legality or
 * budget headroom — clamped to `[0, sliceLengthDays]` as a final safety net
 * regardless of which formula is used.
 */
function targetOffDaysForWeekSlice(
  sliceLengthDays: number,
  daysInMonth: number
): number {
  const raw = Math.round((TARGET_DAYS_OFF_PER_MONTH * sliceLengthDays) / daysInMonth);
  return Math.max(0, Math.min(sliceLengthDays, raw));
}

/**
 * Additional (never a replacement for) weekly eligibility filter alongside
 * `filterCandidatesWithinBudget`, active only when `targetBlockMinutesMax`
 * is set (docs item 21). Returns only candidates that would not push the
 * CURRENT week slice's own running block-minute total past its soft slice
 * plus `WEEKLY_BLOCK_TOLERANCE_FRACTION` tolerance. `weeklyBlockSliceMinutes
 * === undefined` means no weekly budget filtering (mirrors
 * `filterCandidatesWithinBudget`'s own unset-ceiling behavior).
 *
 * EXCEPTION: when `weeklyBlockMinutesSoFar === 0` (nothing accepted in this
 * week slice yet), this filter is a no-op — the month-level filter above
 * remains the sole gate. Without this, a tight month-level budget spread
 * over several week slices can produce a weekly slice smaller than a single
 * real pairing's own block time (e.g. a 1400-min month ceiling over 5 weeks
 * is a 280-min/week slice, smaller than almost any real pairing), which
 * would incorrectly block even a week's very first, otherwise-legal pick —
 * starving the month of flying it could easily afford, not "pacing" it. The
 * whole point of weekly pacing is to stop one week from absorbing SEVERAL
 * pairings' worth of budget that other weeks then go without — it was never
 * meant to block a week's first pairing outright.
 */
function filterCandidatesWithinWeeklyBudget(
  candidates: GeneratedPairing[],
  weeklyBlockMinutesSoFar: number,
  weeklyBlockSliceMinutes: number | undefined
): GeneratedPairing[] {
  if (weeklyBlockSliceMinutes == null) return candidates;
  if (weeklyBlockMinutesSoFar === 0) return candidates;
  const weeklyCeiling = weeklyBlockSliceMinutes * (1 + WEEKLY_BLOCK_TOLERANCE_FRACTION);
  return candidates.filter(
    (candidate) => weeklyBlockMinutesSoFar + pairingBlockMinutes(candidate) <= weeklyCeiling
  );
}

/**
 * Orders one day's ALREADY-budget-filtered eligible candidates for the
 * construction loop below, per `input.generationStrategy`'s doc comment
 * (`GenerationStrategy` in types.ts). Always returns a NEW array
 * (Array#sort is stable, so candidates tied on the sort key keep their
 * existing deterministic-shuffle relative order — route variety among ties
 * is unaffected). Never mutates `candidates` itself, since the same
 * shuffled bucket array is looked up again if this date were ever
 * revisited.
 */
function orderCandidatesByStrategy(
  candidates: GeneratedPairing[],
  strategy: GenerationStrategy,
  haulTypeCountsSoFar: Record<HaulType, number>
): GeneratedPairing[] {
  if (strategy === 'MAX_FLYING') {
    return [...candidates].sort((a, b) => pairingBlockMinutes(a) - pairingBlockMinutes(b));
  }
  if (strategy === 'MAX_DAYS_OFF') {
    return [...candidates].sort((a, b) => pairingBlockMinutes(b) - pairingBlockMinutes(a));
  }
  // MIX (default): prefer whichever haul type is currently
  // least-represented among pairings assigned so far this month.
  return [...candidates].sort(
    (a, b) =>
      haulTypeCountsSoFar[classifyHaulType(a)] - haulTypeCountsSoFar[classifyHaulType(b)]
  );
}

function countDistinctPairings(days: RosterGenDay[]): number {
  const seen = new Set<GeneratedPairing>();
  for (const day of days) {
    if (day.assignment.type === 'FLIGHT') seen.add(day.assignment.pairing);
  }
  return seen.size;
}

/**
 * Generates a full-month FLIGHT/OFF assignment for one fleet type. Pure
 * function — see this module's doc comment for the algorithm and its
 * explicit scope limitations.
 */
export function generateMonthlyRoster(
  input: GenerateMonthlyRosterInput
): MonthlyRosterGenerationResult {
  const {
    fleetType,
    year,
    month,
    pairings,
    airportTimeZones,
    operatorConfig,
    targetBlockMinutesMax,
    generationStrategy = 'MIX',
  } = input;

  const daysInMonth = daysInMonthOf(year, month);
  const dates = Array.from({ length: daysInMonth }, (_, i) => isoDate(year, month, i + 1));

  const candidatesByStart = new Map<string, GeneratedPairing[]>();
  for (const pairing of pairings) {
    const bucket = candidatesByStart.get(pairing.startServiceDate) ?? [];
    bucket.push(pairing);
    candidatesByStart.set(pairing.startServiceDate, bucket);
  }

  const rng = mulberry32(hashSeed(`${fleetType}|${year}|${month}`));
  for (const bucket of candidatesByStart.values()) {
    shuffleInPlace(bucket, rng);
  }

  const days: RosterGenDay[] = [];
  let dayIndex0 = 0; // 0-based cursor
  let daysOffSoFar = 0;
  let runningBlockMinutesSoFar = 0;
  const haulTypeCountsSoFar: Record<HaulType, number> = { SHORT: 0, MEDIUM: 0, LONG: 0 };

  const numSlices = numberOfWeekSlices(daysInMonth);
  const weeklyBlockSliceMinutes =
    targetBlockMinutesMax == null ? undefined : targetBlockMinutesMax / numSlices;
  let currentWeekSliceStart0 = -1; // sentinel — forces a reset on the first iteration
  let weeklyBlockMinutesSoFar = 0;
  let weeklyOffDaysSoFar = 0;

  while (dayIndex0 < daysInMonth) {
    const date = dates[dayIndex0];
    const consecutiveDutyDaysBefore = countConsecutiveDutyDaysAtEnd(days);
    const remainingDaysInMonth = daysInMonth - dayIndex0;

    const { start0: sliceStart0, end0: sliceEnd0 } = weekSliceBoundsForDay(dayIndex0, daysInMonth);
    if (sliceStart0 !== currentWeekSliceStart0) {
      currentWeekSliceStart0 = sliceStart0;
      weeklyBlockMinutesSoFar = 0;
      weeklyOffDaysSoFar = 0;
    }
    const sliceLengthDays = sliceEnd0 - sliceStart0 + 1;
    const remainingDaysInSlice = sliceEnd0 - dayIndex0 + 1;
    const weeklyTargetOffDays = targetOffDaysForWeekSlice(sliceLengthDays, daysInMonth);
    const weeklyStillNeededOff = Math.max(0, weeklyTargetOffDays - weeklyOffDaysSoFar);
    const forcedOffByWeeklyPacing = weeklyStillNeededOff >= remainingDaysInSlice;

    const stillNeeded = Math.max(0, TARGET_DAYS_OFF_PER_MONTH - daysOffSoFar);
    const forcedOffByPacing =
      dayIndex0 + 1 >= PACING_CHECK_FROM_DAY && stillNeeded >= remainingDaysInMonth;
    const forcedOffByConsecutiveCap =
      consecutiveDutyDaysBefore >= CONSECUTIVE_DUTY_DAYS_SOFT_CAP;

    let assignedPairing: GeneratedPairing | null = null;

    if (!forcedOffByPacing && !forcedOffByConsecutiveCap && !forcedOffByWeeklyPacing) {
      const candidates = candidatesByStart.get(date) ?? [];
      const monthBudgetFiltered = filterCandidatesWithinBudget(
        candidates,
        runningBlockMinutesSoFar,
        targetBlockMinutesMax
      );
      const eligibleCandidates = filterCandidatesWithinWeeklyBudget(
        monthBudgetFiltered,
        weeklyBlockMinutesSoFar,
        weeklyBlockSliceMinutes
      );
      const orderedCandidates = orderCandidatesByStrategy(
        eligibleCandidates,
        generationStrategy,
        haulTypeCountsSoFar
      );
      for (const candidate of orderedCandidates) {
        if (dayIndex0 + candidate.tripDays > daysInMonth) continue; // wouldn't fit in the month
        if (consecutiveDutyDaysBefore + candidate.tripDays > MAX_CONSECUTIVE_DUTY_DAYS) continue;
        // Would this multi-day candidate itself consume enough of the
        // CURRENT week slice's remaining days that the slice's own
        // days-off target becomes unreachable afterward? Without this
        // guard, a pairing accepted here could span straight past the
        // single day where `forcedOffByWeeklyPacing` would otherwise have
        // fired later this same slice — the day-level check above only
        // ever runs at whichever day the loop's cursor actually lands on,
        // and a multi-day pairing's own span is never individually
        // revisited (docs item 21).
        const remainingDaysInSliceAfterCandidate = Math.max(
          0,
          remainingDaysInSlice - candidate.tripDays
        );
        if (remainingDaysInSliceAfterCandidate < weeklyStillNeededOff) continue;

        const candidateDays = buildCandidateDays(candidate, dates, dayIndex0);
        const hypothetical = [...days, ...candidateDays];
        const candidateDates = new Set(candidateDays.map((d) => d.date));
        const evaluations = evaluateRosterDays(hypothetical, airportTimeZones, operatorConfig);
        const hasRed = evaluations.some(
          (e) => candidateDates.has(e.date) && e.evaluation.severity === 'RED'
        );

        if (!hasRed) {
          assignedPairing = candidate;
          days.push(...candidateDays);
          dayIndex0 += candidate.tripDays;
          runningBlockMinutesSoFar += pairingBlockMinutes(candidate);
          weeklyBlockMinutesSoFar += pairingBlockMinutes(candidate);
          haulTypeCountsSoFar[classifyHaulType(candidate)] += 1;
          break;
        }
      }
    }

    if (!assignedPairing) {
      days.push({ date, assignment: { type: 'OFF' } });
      daysOffSoFar += 1;
      weeklyOffDaysSoFar += 1;
      dayIndex0 += 1;
    }
  }

  const evaluations = evaluateRosterDays(days, airportTimeZones, operatorConfig);
  const flightDays = days.filter((d) => d.assignment.type === 'FLIGHT').length;

  return {
    fleetType,
    year,
    month,
    days,
    evaluations,
    summary: {
      flightDays,
      offDays: days.length - flightDays,
      totalBlockMinutes: sumBlockMinutes(days),
      pairingsAssigned: countDistinctPairings(days),
    },
  };
}
