import type { Metadata } from "next";
import { Barlow, Barlow_Semi_Condensed } from "next/font/google";
import { ComplianceBanner } from "@/components/ComplianceBanner";
import "./globals.css";

const barlowSans = Barlow({
  variable: "--font-barlow-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const barlowDisplay = Barlow_Semi_Condensed({
  variable: "--font-barlow-display",
  subsets: ["latin"],
  weight: ["500", "600"],
});

export const metadata: Metadata = {
  title: "Roster lab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${barlowSans.variable} ${barlowDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ComplianceBanner />
        {children}
      </body>
    </html>
  );
}
