/**
 * Phase 5 Slice 1 — reconstructs a `RosterGenDay[]` from what's actually
 * PERSISTED in the DB (`RosterEntry` rows, which may be manually assembled
 * via the Phase 2 constructor, not just auto-generated by Phase 4), so the
 * real `src/roster-gen/generateMonthlyRoster.ts#evaluateRosterDays` can be
 * re-run against a live persisted roster — not just a freshly-generated one
 * (`src/roster-gen/db/rosterGen.ts#buildMonthlyRosterForFleet` is the only
 * existing caller of `evaluateRosterDays`, and it only ever sees a roster it
 * just built in memory).
 *
 * Reuses `src/pairing/db/roster.ts#buildRosterGrid` for the FLIGHT
 * continuation-day expansion (start day + spansDays continuation days, with
 * the correct incrementing `dayOfPairing`) instead of re-implementing it —
 * `buildRosterGrid` already performs exactly this expansion for the roster
 * grid UI, so this module only adds the pairing-id -> `GeneratedPairing`
 * resolution on top of it.
 *
 * JUDGMENT CALL (approved, logged in docs/roster-gen-assumptions.md): a day
 * with no RosterEntry, or a RosterEntry whose `dutyType` is one of
 * `STANDBY` / `SIM` / `GROUND_SCHOOL` / `VACATION`, is mapped to
 * `{ type: 'OFF' }` for evaluation purposes. The Phase 4 generator itself
 * never produces these duty types (see docs/roster-gen-assumptions.md item
 * 8), but a persisted roster CAN carry them (assigned manually via Phase 2's
 * constructor), and `evaluateRosterDays` only knows FLIGHT/OFF.
 */

import type { PrismaClient } from '@prisma/client';
import { buildRosterGrid, listRosterEntries } from '../../pairing/db/roster';
import { loadPairingById } from '../../pairing/db/loadPairing';
import type { GeneratedPairing } from '../../pairing/types';
import type { RosterGenDay } from '../types';

export async function loadRosterGenDaysForMonth(
  prisma: PrismaClient,
  rosterMonthId: string,
  year: number,
  month: number
): Promise<RosterGenDay[]> {
  const entries = await listRosterEntries(prisma, rosterMonthId);
  const cells = buildRosterGrid(year, month, entries);

  const pairingCache = new Map<string, GeneratedPairing>();
  const days: RosterGenDay[] = [];

  for (const cell of cells) {
    if (cell.entry && cell.entry.dutyType === 'FLIGHT') {
      if (!cell.entry.pairingId) {
        throw new Error(
          `loadRosterGenDaysForMonth: RosterEntry ${cell.entry.id} on ${cell.date} has ` +
            `dutyType FLIGHT but no pairingId — malformed data.`
        );
      }

      let pairing = pairingCache.get(cell.entry.pairingId);
      if (!pairing) {
        pairing = await loadPairingById(prisma, cell.entry.pairingId);
        pairingCache.set(cell.entry.pairingId, pairing);
      }

      days.push({
        date: cell.date,
        assignment: { type: 'FLIGHT', pairing, dayOfPairing: cell.dayOfPairing ?? 1 },
      });
      continue;
    }

    // No entry at all, OR an entry whose dutyType is OFF / STANDBY / SIM /
    // GROUND_SCHOOL / VACATION — all treated as OFF-equivalent for live
    // GCAA re-evaluation purposes (see this module's doc comment and
    // docs/roster-gen-assumptions.md).
    days.push({ date: cell.date, assignment: { type: 'OFF' } });
  }

  return days;
}
